services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: janken
      POSTGRES_PASSWORD: janken
      POSTGRES_DB: janken
    ports: ['5432:5432']
    volumes: ['janken-pg:/var/lib/postgresql/data']
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U janken']
      interval: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports: ['6379:6379']

volumes:
  janken-pg:
